name: Build and Deploy with Manual Approvals

on:
  push:
    branches:
      - dev
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    environment:
          name: dev
    outputs:
      build-path: ./client/dist

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          cd client
          npm install

      - name: Create environment file
        run: |
          cd client
          echo "📦 Creating .env file"
          echo "VITE_API_BASE_URL=${{ vars.VITE_API_BASE_URL }}" > .env
      - name: Check .env file content (debug)
        run: |
          cd client
          echo "📄 Contents of .env file:"
          cat .env

      - name: Print environment variables
        run: |
          echo "🧪 GitHub Environment: ${{ github.ref }}"
          echo "🧪 VITE_API_BASE_URL from GitHub Environment: ${{ vars.VITE_API_BASE_URL }}"

      - name: Build project (Vite)
        run: |
          cd client
          if [ "${{ github.ref }}" == "refs/heads/dev" ]; then
            echo "🚧 Building for DEV"
            npm run build:dev
          else
            echo "🚧 Building for PROD"
            npm run build:prod
          fi

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-dist
          path: client/dist

  deploy-dev:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: dev
      url: https://RahamimLazimi.github.io/support-dashboard/dev/
    if: github.ref == 'refs/heads/dev'

    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: build-dist
          path: ./client/dist

      - name: Deploy to GitHub Pages (dev)
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.PAT_TOKEN }}
          publish_dir: ./client/dist
          publish_branch: gh-pages
          destination_dir: dev
          user_name: github-actions[bot]
          user_email: github-actions[bot]@users.noreply.github.com


  deploy-prod:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: prod
      url: https://RahamimLazimi.github.io/support-dashboard/prod/
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: build-dist
          path: ./client/dist

      - name: Deploy to GitHub Pages (prod)
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.PAT_TOKEN }}
          publish_dir: ./client/dist
          publish_branch: gh-pages
          destination_dir: prod
          user_name: github-actions[bot]
          user_email: github-actions[bot]@users.noreply.github.com
